# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GUI(object):
    def setupUi(self, GUI):
        GUI.setObjectName("GUI")
        GUI.resize(1230, 672)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(238, 238, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(231, 183, 112))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(238, 238, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(231, 183, 112))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(238, 238, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(231, 183, 112))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(231, 183, 112))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        #GUI.setPalette(palette)
        GUI.setAutoFillBackground(False)
        self.groupBox_color = QtWidgets.QGroupBox(GUI)
        self.groupBox_color.setGeometry(QtCore.QRect(20, 20, 390, 121))
        self.groupBox_color.setTitle("Цвета")
        self.groupBox_color.setObjectName("groupBox_color")

        self.groupBox_input = QtWidgets.QGroupBox(GUI)
        self.groupBox_input.setGeometry(QtCore.QRect(20, 210, 390, 251))
        self.groupBox_input.setTitle("Ввод")
        self.groupBox_input.setObjectName("groupBox_input")

        self.graphicsView = QtWidgets.QGraphicsView(GUI)
        self.graphicsView.setGeometry(QtCore.QRect(460, 10, 761, 651))
        self.graphicsView.setObjectName("graphicsView")
        self.label = QtWidgets.QLabel(self.groupBox_color)
        self.label.setGeometry(QtCore.QRect(10, 20, 121, 31))
        self.label.setStyleSheet("font: 9pt \"Ubuntu\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox_color)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 150, 31))
        self.label_2.setStyleSheet("font: 9pt \"Ubuntu\";")
        self.label_2.setObjectName("label_2")

        self.cutterButton = QtWidgets.QPushButton(GUI)
        self.cutterButton.setGeometry(QtCore.QRect(40, 560, 350, 35))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.cutterButton.setFont(font)
        self.cutterButton.setStyleSheet("QPushButton {"
                              "display: inline-block;"
                              "font-size: 18px;"
                              "cursor: pointer;"
                              "text-align: center;"
                              "text-decoration: none;"
                              "outline: none;"
                              "color: #fff;"
                              "background-color: #F8D131;"
                              "border: none;"
                              "border-radius: 10px;"
                              "box-shadow: 0 9px #999;"
                            "}"
                            "QPushButton:hover {background-color: #DBB51C}"
                            "QPushButton:pressed {"
                              "background-color: #DBB51C;"
                              "box-shadow: 0 5px #666;"
                              "transform: translateY(4px);"
                            "}")
        self.cutterButton.setObjectName("cutterButton")

        self.clearScreenButton = QtWidgets.QPushButton(GUI)
        self.clearScreenButton.setGeometry(QtCore.QRect(40, 600, 350, 35))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.clearScreenButton.setFont(font)
        self.clearScreenButton.setStyleSheet("QPushButton {"
                              "display: inline-block;"
                              "font-size: 18px;"
                              "cursor: pointer;"
                              "text-align: center;"
                              "text-decoration: none;"
                              "outline: none;"
                              "color: #fff;"
                              "background-color: #DC143C;"
                              "border: none;"
                              "border-radius: 10px;"
                              "box-shadow: 0 9px #999;"
                            "}"
                            "QPushButton:hover {background-color: #B22222}"
                            "QPushButton:pressed {"
                              "background-color: #B22222;"
                              "box-shadow: 0 5px #666;"
                              "transform: translateY(4px);"
                            "}")
        self.clearScreenButton.setObjectName("clearScreenButton")

        self.label_10 = QtWidgets.QLabel(self.groupBox_input)
        self.label_10.setGeometry(QtCore.QRect(50, 50, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.groupBox_input)
        self.label_11.setGeometry(QtCore.QRect(230, 50, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.X_box = QtWidgets.QLineEdit(self.groupBox_input)
        self.X_box.setGeometry(QtCore.QRect(100, 50, 71, 31))
        self.X_box.setObjectName("X_box")
        self.Y_box = QtWidgets.QLineEdit(self.groupBox_input)
        self.Y_box.setGeometry(QtCore.QRect(270, 50, 71, 31))
        self.Y_box.setObjectName("Y_box")

        self.addSegmentButton = QtWidgets.QPushButton(self.groupBox_input)
        self.addSegmentButton.setGeometry(QtCore.QRect(20, 120, 350, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.addSegmentButton.setFont(font)
        self.addSegmentButton.setStyleSheet("QPushButton {"
                                  "display: inline-block;"
                                  "font-size: 18px;"
                                  "cursor: pointer;"
                                  "text-align: center;"
                                  "text-decoration: none;"
                                  "outline: none;"
                                  "color: #fff;"
                                  "background-color: #4CAF50;"
                                  "border: none;"
                                  "border-radius: 10px;"
                                  "box-shadow: 0 9px #999;"
                                "}"
                                "QPushButton:hover {background-color: #3e8e41}"
                                "QPushButton:pressed {"
                                  "background-color: #3e8e41;"
                                  "box-shadow: 0 5px #666;"
                                  "transform: translateY(4px);"
                                "}")
        self.addSegmentButton.setObjectName("addSegmentButton")

        self.label_4 = QtWidgets.QLabel(self.groupBox_input)
        self.label_4.setGeometry(QtCore.QRect(50, 15, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_color)
        self.label_5.setGeometry(QtCore.QRect(10, 80, 111, 31))
        self.label_5.setStyleSheet("font: 9pt \"Ubuntu\";")
        self.label_5.setObjectName("label_5")

        self.cutOff_colorButton = QtWidgets.QPushButton(self.groupBox_color)
        self.cutOff_colorButton.setGeometry(QtCore.QRect(120, 21, 25, 25))
        self.cutOff_colorButton.setText("")
        self.cutOff_colorButton.setObjectName("cutOff_colorButton")

        self.segment_olorButton = QtWidgets.QPushButton(self.groupBox_color)
        self.segment_olorButton.setGeometry(QtCore.QRect(160, 51, 25, 25))
        self.segment_olorButton.setText("")
        self.segment_olorButton.setObjectName("segment_olorButton")

        self.result_colorButton = QtWidgets.QPushButton(self.groupBox_color)
        self.result_colorButton.setGeometry(QtCore.QRect(110, 81, 25, 25))
        self.result_colorButton.setText("")
        self.result_colorButton.setObjectName("result_colorButton")

        self.lockCutterButton = QtWidgets.QPushButton(self.groupBox_input)
        self.lockCutterButton.setGeometry(QtCore.QRect(20, 160, 350, 35))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lockCutterButton.setFont(font)
        self.lockCutterButton.setStyleSheet("QPushButton {"
                                  "display: inline-block;"
                                  "font-size: 18px;"
                                  "cursor: pointer;"
                                  "text-align: center;"
                                  "text-decoration: none;"
                                  "outline: none;"
                                  "color: #fff;"
                                  "background-color: #4CAF50;"
                                  "border: none;"
                                  "border-radius: 10px;"
                                  "box-shadow: 0 9px #999;"
                                "}"
                                "QPushButton:hover {background-color: #3e8e41}"
                                "QPushButton:pressed {"
                                  "background-color: #3e8e41;"
                                  "box-shadow: 0 5px #666;"
                                  "transform: translateY(4px);"
                                "}")
        self.lockCutterButton.setObjectName("lockCutterButton")

        self.groupBox = QtWidgets.QGroupBox(GUI)
        self.groupBox.setGeometry(QtCore.QRect(20, 150, 390, 51))
        self.groupBox.setTitle("Режим")
        self.groupBox.setObjectName("groupBox")
        self.segmentRadio = QtWidgets.QRadioButton(self.groupBox)
        self.segmentRadio.setGeometry(QtCore.QRect(40, 20, 112, 23))
        self.segmentRadio.setChecked(True)
        self.segmentRadio.setObjectName("segmentRadio")
        self.cutterRadio = QtWidgets.QRadioButton(self.groupBox)
        self.cutterRadio.setGeometry(QtCore.QRect(230, 20, 112, 23))
        self.cutterRadio.setObjectName("cutterRadio")

        self.curPointLabel = QtWidgets.QLabel(self.groupBox_input)
        self.curPointLabel.setGeometry(QtCore.QRect(150, 80, 120, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.curPointLabel.setFont(font)
        self.curPointLabel.setText("")
        self.curPointLabel.setObjectName("curPointLabel")

        self.delCutterButton = QtWidgets.QPushButton(self.groupBox_input)
        self.delCutterButton.setEnabled(False)
        self.delCutterButton.setGeometry(QtCore.QRect(20, 200, 350, 35))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.delCutterButton.setFont(font)
        self.delCutterButton.setStyleSheet("QPushButton {"
                                  "display: inline-block;"
                                  "font-size: 18px;"
                                  "cursor: pointer;"
                                  "text-align: center;"
                                  "text-decoration: none;"
                                  "outline: none;"
                                  "color: #fff;"
                                  "background-color: #4CAF50;"
                                  "border: none;"
                                  "border-radius: 10px;"
                                  "box-shadow: 0 9px #999;"
                                "}"
                                "QPushButton:hover {background-color: #3e8e41}"
                                "QPushButton:disabled {background-color: #3e8e41}"
                                "QPushButton:pressed {"
                                  "background-color: #3e8e41;"
                                  "box-shadow: 0 5px #666;"
                                  "transform: translateY(4px);"
                                "}")
        self.delCutterButton.setObjectName("delCutterButton")

        self.retranslateUi(GUI)
        QtCore.QMetaObject.connectSlotsByName(GUI)

    def retranslateUi(self, GUI):
        _translate = QtCore.QCoreApplication.translate
        GUI.setWindowTitle(_translate("GUI", "Лаба 9"))
        self.label.setText(_translate("GUI", "Отсекатель"))
        self.label_2.setText(_translate("GUI", "Многоугольники"))
        self.cutterButton.setText(_translate("GUI", "Отсечь"))
        self.clearScreenButton.setText(_translate("GUI", "Очистить экран"))
        self.label_10.setText(_translate("GUI", "X"))
        self.label_11.setText(_translate("GUI", "Y"))
        self.X_box.setText(_translate("GUI", "100"))
        self.Y_box.setText(_translate("GUI", "100"))
        self.addSegmentButton.setText(_translate("GUI", "Добавить точку многоугольника"))
        self.label_4.setText(_translate("GUI", "Ввод точки многоугольника"))
        self.label_5.setText(_translate("GUI", "Результат"))
        self.lockCutterButton.setText(_translate("GUI", "Замкнуть"))
        self.segmentRadio.setText(_translate("GUI", "Отрезок"))
        self.cutterRadio.setText(_translate("GUI", "Отсекатель"))
        self.delCutterButton.setText(_translate("GUI", "Удалить отсекатель"))